<?php
/**
 * ApiAfterSaleVo
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * 电商开放平台接口说明--深圳小于科技
 *
 * 小于电商平台开放接口是指每家企业可以拥有一套独立的密钥信息（AppId 与 AppSecret），通过这套密钥信息来调用电商平台公布出来的企业相关的开放接口，比如店铺、商品、订单等数据接口。您可以在 【开放平台】 - 【控制台】 - 【应用管理】 中进行管理，请务必妥善保管。
 *
 * The version of the OpenAPI document: 1.8.0
 * Contact: 393341261@qq.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\com.lessthan.openapi.model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ApiAfterSaleVo Class Doc Comment
 *
 * @category Class
 * @description 售后
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ApiAfterSaleVo implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ApiAfterSaleVo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'platform_shop_id' => 'string',
        'platform_order_id' => 'string',
        'platform_after_sale_id' => 'string',
        'third_platform' => 'string',
        'platform_shop_no' => 'string',
        'after_sale_no' => 'string',
        'order_no' => 'string',
        'apply_time' => 'string',
        'after_sale_type' => 'string',
        'after_sale_type_value' => 'string',
        'after_sale_amount' => 'float',
        'after_sale_count' => 'int',
        'after_sale_status' => 'string',
        'after_sale_status_value' => 'string',
        'reason' => 'string',
        'update_time' => 'string',
        'other_info' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'platform_shop_id' => null,
        'platform_order_id' => null,
        'platform_after_sale_id' => null,
        'third_platform' => null,
        'platform_shop_no' => null,
        'after_sale_no' => null,
        'order_no' => null,
        'apply_time' => null,
        'after_sale_type' => null,
        'after_sale_type_value' => null,
        'after_sale_amount' => null,
        'after_sale_count' => null,
        'after_sale_status' => null,
        'after_sale_status_value' => null,
        'reason' => null,
        'update_time' => null,
        'other_info' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'platform_shop_id' => false,
		'platform_order_id' => false,
		'platform_after_sale_id' => false,
		'third_platform' => false,
		'platform_shop_no' => false,
		'after_sale_no' => false,
		'order_no' => false,
		'apply_time' => false,
		'after_sale_type' => false,
		'after_sale_type_value' => false,
		'after_sale_amount' => false,
		'after_sale_count' => false,
		'after_sale_status' => false,
		'after_sale_status_value' => false,
		'reason' => false,
		'update_time' => false,
		'other_info' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'platform_shop_id' => 'platformShopId',
        'platform_order_id' => 'platformOrderId',
        'platform_after_sale_id' => 'platformAfterSaleId',
        'third_platform' => 'thirdPlatform',
        'platform_shop_no' => 'platformShopNo',
        'after_sale_no' => 'afterSaleNo',
        'order_no' => 'orderNo',
        'apply_time' => 'applyTime',
        'after_sale_type' => 'afterSaleType',
        'after_sale_type_value' => 'afterSaleTypeValue',
        'after_sale_amount' => 'afterSaleAmount',
        'after_sale_count' => 'afterSaleCount',
        'after_sale_status' => 'afterSaleStatus',
        'after_sale_status_value' => 'afterSaleStatusValue',
        'reason' => 'reason',
        'update_time' => 'updateTime',
        'other_info' => 'otherInfo'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'platform_shop_id' => 'setPlatformShopId',
        'platform_order_id' => 'setPlatformOrderId',
        'platform_after_sale_id' => 'setPlatformAfterSaleId',
        'third_platform' => 'setThirdPlatform',
        'platform_shop_no' => 'setPlatformShopNo',
        'after_sale_no' => 'setAfterSaleNo',
        'order_no' => 'setOrderNo',
        'apply_time' => 'setApplyTime',
        'after_sale_type' => 'setAfterSaleType',
        'after_sale_type_value' => 'setAfterSaleTypeValue',
        'after_sale_amount' => 'setAfterSaleAmount',
        'after_sale_count' => 'setAfterSaleCount',
        'after_sale_status' => 'setAfterSaleStatus',
        'after_sale_status_value' => 'setAfterSaleStatusValue',
        'reason' => 'setReason',
        'update_time' => 'setUpdateTime',
        'other_info' => 'setOtherInfo'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'platform_shop_id' => 'getPlatformShopId',
        'platform_order_id' => 'getPlatformOrderId',
        'platform_after_sale_id' => 'getPlatformAfterSaleId',
        'third_platform' => 'getThirdPlatform',
        'platform_shop_no' => 'getPlatformShopNo',
        'after_sale_no' => 'getAfterSaleNo',
        'order_no' => 'getOrderNo',
        'apply_time' => 'getApplyTime',
        'after_sale_type' => 'getAfterSaleType',
        'after_sale_type_value' => 'getAfterSaleTypeValue',
        'after_sale_amount' => 'getAfterSaleAmount',
        'after_sale_count' => 'getAfterSaleCount',
        'after_sale_status' => 'getAfterSaleStatus',
        'after_sale_status_value' => 'getAfterSaleStatusValue',
        'reason' => 'getReason',
        'update_time' => 'getUpdateTime',
        'other_info' => 'getOtherInfo'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('platform_shop_id', $data ?? [], null);
        $this->setIfExists('platform_order_id', $data ?? [], null);
        $this->setIfExists('platform_after_sale_id', $data ?? [], null);
        $this->setIfExists('third_platform', $data ?? [], null);
        $this->setIfExists('platform_shop_no', $data ?? [], null);
        $this->setIfExists('after_sale_no', $data ?? [], null);
        $this->setIfExists('order_no', $data ?? [], null);
        $this->setIfExists('apply_time', $data ?? [], null);
        $this->setIfExists('after_sale_type', $data ?? [], null);
        $this->setIfExists('after_sale_type_value', $data ?? [], null);
        $this->setIfExists('after_sale_amount', $data ?? [], null);
        $this->setIfExists('after_sale_count', $data ?? [], null);
        $this->setIfExists('after_sale_status', $data ?? [], null);
        $this->setIfExists('after_sale_status_value', $data ?? [], null);
        $this->setIfExists('reason', $data ?? [], null);
        $this->setIfExists('update_time', $data ?? [], null);
        $this->setIfExists('other_info', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets platform_shop_id
     *
     * @return string|null
     */
    public function getPlatformShopId()
    {
        return $this->container['platform_shop_id'];
    }

    /**
     * Sets platform_shop_id
     *
     * @param string|null $platform_shop_id 店铺ID，唯一值
     *
     * @return self
     */
    public function setPlatformShopId($platform_shop_id)
    {
        if (is_null($platform_shop_id)) {
            throw new \InvalidArgumentException('non-nullable platform_shop_id cannot be null');
        }
        $this->container['platform_shop_id'] = $platform_shop_id;

        return $this;
    }

    /**
     * Gets platform_order_id
     *
     * @return string|null
     */
    public function getPlatformOrderId()
    {
        return $this->container['platform_order_id'];
    }

    /**
     * Sets platform_order_id
     *
     * @param string|null $platform_order_id 订单ID，唯一值
     *
     * @return self
     */
    public function setPlatformOrderId($platform_order_id)
    {
        if (is_null($platform_order_id)) {
            throw new \InvalidArgumentException('non-nullable platform_order_id cannot be null');
        }
        $this->container['platform_order_id'] = $platform_order_id;

        return $this;
    }

    /**
     * Gets platform_after_sale_id
     *
     * @return string|null
     */
    public function getPlatformAfterSaleId()
    {
        return $this->container['platform_after_sale_id'];
    }

    /**
     * Sets platform_after_sale_id
     *
     * @param string|null $platform_after_sale_id 售后ID，唯一值
     *
     * @return self
     */
    public function setPlatformAfterSaleId($platform_after_sale_id)
    {
        if (is_null($platform_after_sale_id)) {
            throw new \InvalidArgumentException('non-nullable platform_after_sale_id cannot be null');
        }
        $this->container['platform_after_sale_id'] = $platform_after_sale_id;

        return $this;
    }

    /**
     * Gets third_platform
     *
     * @return string|null
     */
    public function getThirdPlatform()
    {
        return $this->container['third_platform'];
    }

    /**
     * Sets third_platform
     *
     * @param string|null $third_platform 对接平台，见【字典数据】
     *
     * @return self
     */
    public function setThirdPlatform($third_platform)
    {
        if (is_null($third_platform)) {
            throw new \InvalidArgumentException('non-nullable third_platform cannot be null');
        }
        $this->container['third_platform'] = $third_platform;

        return $this;
    }

    /**
     * Gets platform_shop_no
     *
     * @return string|null
     */
    public function getPlatformShopNo()
    {
        return $this->container['platform_shop_no'];
    }

    /**
     * Sets platform_shop_no
     *
     * @param string|null $platform_shop_no 平台店铺ID
     *
     * @return self
     */
    public function setPlatformShopNo($platform_shop_no)
    {
        if (is_null($platform_shop_no)) {
            throw new \InvalidArgumentException('non-nullable platform_shop_no cannot be null');
        }
        $this->container['platform_shop_no'] = $platform_shop_no;

        return $this;
    }

    /**
     * Gets after_sale_no
     *
     * @return string|null
     */
    public function getAfterSaleNo()
    {
        return $this->container['after_sale_no'];
    }

    /**
     * Sets after_sale_no
     *
     * @param string|null $after_sale_no 售后编号
     *
     * @return self
     */
    public function setAfterSaleNo($after_sale_no)
    {
        if (is_null($after_sale_no)) {
            throw new \InvalidArgumentException('non-nullable after_sale_no cannot be null');
        }
        $this->container['after_sale_no'] = $after_sale_no;

        return $this;
    }

    /**
     * Gets order_no
     *
     * @return string|null
     */
    public function getOrderNo()
    {
        return $this->container['order_no'];
    }

    /**
     * Sets order_no
     *
     * @param string|null $order_no 订单编号
     *
     * @return self
     */
    public function setOrderNo($order_no)
    {
        if (is_null($order_no)) {
            throw new \InvalidArgumentException('non-nullable order_no cannot be null');
        }
        $this->container['order_no'] = $order_no;

        return $this;
    }

    /**
     * Gets apply_time
     *
     * @return string|null
     */
    public function getApplyTime()
    {
        return $this->container['apply_time'];
    }

    /**
     * Sets apply_time
     *
     * @param string|null $apply_time 申请时间，格式： yyyy-MM-dd HH:mm:ss
     *
     * @return self
     */
    public function setApplyTime($apply_time)
    {
        if (is_null($apply_time)) {
            throw new \InvalidArgumentException('non-nullable apply_time cannot be null');
        }
        $this->container['apply_time'] = $apply_time;

        return $this;
    }

    /**
     * Gets after_sale_type
     *
     * @return string|null
     */
    public function getAfterSaleType()
    {
        return $this->container['after_sale_type'];
    }

    /**
     * Sets after_sale_type
     *
     * @param string|null $after_sale_type 售后类型，如：退货退款，见【字典数据】
     *
     * @return self
     */
    public function setAfterSaleType($after_sale_type)
    {
        if (is_null($after_sale_type)) {
            throw new \InvalidArgumentException('non-nullable after_sale_type cannot be null');
        }
        $this->container['after_sale_type'] = $after_sale_type;

        return $this;
    }

    /**
     * Gets after_sale_type_value
     *
     * @return string|null
     */
    public function getAfterSaleTypeValue()
    {
        return $this->container['after_sale_type_value'];
    }

    /**
     * Sets after_sale_type_value
     *
     * @param string|null $after_sale_type_value 售后类型值，如：0，见【字典数据】
     *
     * @return self
     */
    public function setAfterSaleTypeValue($after_sale_type_value)
    {
        if (is_null($after_sale_type_value)) {
            throw new \InvalidArgumentException('non-nullable after_sale_type_value cannot be null');
        }
        $this->container['after_sale_type_value'] = $after_sale_type_value;

        return $this;
    }

    /**
     * Gets after_sale_amount
     *
     * @return float|null
     */
    public function getAfterSaleAmount()
    {
        return $this->container['after_sale_amount'];
    }

    /**
     * Sets after_sale_amount
     *
     * @param float|null $after_sale_amount 售后金额，最多保留4位小数
     *
     * @return self
     */
    public function setAfterSaleAmount($after_sale_amount)
    {
        if (is_null($after_sale_amount)) {
            throw new \InvalidArgumentException('non-nullable after_sale_amount cannot be null');
        }
        $this->container['after_sale_amount'] = $after_sale_amount;

        return $this;
    }

    /**
     * Gets after_sale_count
     *
     * @return int|null
     */
    public function getAfterSaleCount()
    {
        return $this->container['after_sale_count'];
    }

    /**
     * Sets after_sale_count
     *
     * @param int|null $after_sale_count 售后数量
     *
     * @return self
     */
    public function setAfterSaleCount($after_sale_count)
    {
        if (is_null($after_sale_count)) {
            throw new \InvalidArgumentException('non-nullable after_sale_count cannot be null');
        }
        $this->container['after_sale_count'] = $after_sale_count;

        return $this;
    }

    /**
     * Gets after_sale_status
     *
     * @return string|null
     */
    public function getAfterSaleStatus()
    {
        return $this->container['after_sale_status'];
    }

    /**
     * Sets after_sale_status
     *
     * @param string|null $after_sale_status 售后状态，如：售后成功，见【字典数据】
     *
     * @return self
     */
    public function setAfterSaleStatus($after_sale_status)
    {
        if (is_null($after_sale_status)) {
            throw new \InvalidArgumentException('non-nullable after_sale_status cannot be null');
        }
        $this->container['after_sale_status'] = $after_sale_status;

        return $this;
    }

    /**
     * Gets after_sale_status_value
     *
     * @return string|null
     */
    public function getAfterSaleStatusValue()
    {
        return $this->container['after_sale_status_value'];
    }

    /**
     * Sets after_sale_status_value
     *
     * @param string|null $after_sale_status_value 售后状态值，如：12，见【字典数据】
     *
     * @return self
     */
    public function setAfterSaleStatusValue($after_sale_status_value)
    {
        if (is_null($after_sale_status_value)) {
            throw new \InvalidArgumentException('non-nullable after_sale_status_value cannot be null');
        }
        $this->container['after_sale_status_value'] = $after_sale_status_value;

        return $this;
    }

    /**
     * Gets reason
     *
     * @return string|null
     */
    public function getReason()
    {
        return $this->container['reason'];
    }

    /**
     * Sets reason
     *
     * @param string|null $reason 售后原因
     *
     * @return self
     */
    public function setReason($reason)
    {
        if (is_null($reason)) {
            throw new \InvalidArgumentException('non-nullable reason cannot be null');
        }
        $this->container['reason'] = $reason;

        return $this;
    }

    /**
     * Gets update_time
     *
     * @return string|null
     */
    public function getUpdateTime()
    {
        return $this->container['update_time'];
    }

    /**
     * Sets update_time
     *
     * @param string|null $update_time 数据更新时间，格式： yyyy-MM-dd HH:mm:ss
     *
     * @return self
     */
    public function setUpdateTime($update_time)
    {
        if (is_null($update_time)) {
            throw new \InvalidArgumentException('non-nullable update_time cannot be null');
        }
        $this->container['update_time'] = $update_time;

        return $this;
    }

    /**
     * Gets other_info
     *
     * @return string|null
     */
    public function getOtherInfo()
    {
        return $this->container['other_info'];
    }

    /**
     * Sets other_info
     *
     * @param string|null $other_info 其他信息JSON字符串，每个平台定制字段，见【字典数据】
     *
     * @return self
     */
    public function setOtherInfo($other_info)
    {
        if (is_null($other_info)) {
            throw new \InvalidArgumentException('non-nullable other_info cannot be null');
        }
        $this->container['other_info'] = $other_info;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


